### ISSUE TITLE
Package version conflict

### ISSUE THREAD

**Issue by Ayumu-J-S** [fathomnet/fgvc-comp-2023#4]
I am using conda with python=3.8, and I get a conflict like below.

```
The conflict is caused by:
    The user requested numpy==1.23.5
    bottleneck 1.3.5 depends on numpy
    mkl-fft 1.3.1 depends on numpy<1.23.0 and >=1.22.3
```

Any idea??

**Comment by eor314** [comment]
Thanks for pointing this out. The current version works with python>=3.10. I'll work on a revision to `requirements.txt` that works with older versions. 

In the meantime, if you change line 12 in `requirements.txt` to:

```
numpy==1.22.4
```

you should be able to install everything for python=3.8

**Comment by eor314** [comment]
Version has been updated in requirements and instructions for installation added to the README.
